name: Slack Notify
on: [issues, issue_comment, project_card, pull_request]

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
            payload: | 
                {
                    "attachments": [
                    {
                        "color": "#d90000",
                        "blocks": [
                        {
                            "type": "section",
                            "text": {
                            "type": "mrkdwn",
                            "text": "${{ github.workflow }} workflow failed on ${{ env.DEFAULT_BRANCH }} branch in the ${{ github.event.repository.name }} repository!"
                            }
                        },
                        {
                            "type": "divider"
                        },
                        {
                            "type": "actions",
                            "elements": [
                            {
                                "type": "button",
                                "text": {
                                "type": "plain_text",
                                "text": "Build",
                                "emoji": true
                                },
                                "url": "${{ env.REPO_URL }}/actions/runs/${{ github.run_id }}"
                            },
                            {
                                "type": "button",
                                "text": {
                                "type": "plain_text",
                                "text": "Commit",
                                "emoji": true
                                },
                                "url": "${{ env.REPO_URL }}/commit/${{ github.sha }}"
                            }
                            ]
                        }
                        ]
                    }
                    ]
                }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}